// Code generated by go-swagger; DO NOT EDIT.

package checkout_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// PlaceOrderReader is a Reader for the PlaceOrder structure.
type PlaceOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPlaceOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPlaceOrderOK creates a PlaceOrderOK with default headers values
func NewPlaceOrderOK() *PlaceOrderOK {
	return &PlaceOrderOK{}
}

/*PlaceOrderOK handles this case with default header values.

A successful response.
*/
type PlaceOrderOK struct {
	Payload *models.HipstershopPlaceOrderResponse
}

func (o *PlaceOrderOK) Error() string {
	return fmt.Sprintf("[POST /orders/checkout][%d] placeOrderOK  %+v", 200, o.Payload)
}

func (o *PlaceOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopPlaceOrderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
