// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HipstershopGetSupportedCurrenciesResponse hipstershop get supported currencies response
// swagger:model hipstershopGetSupportedCurrenciesResponse
type HipstershopGetSupportedCurrenciesResponse struct {

	// The 3-letter currency code defined in ISO 4217.
	CurrencyCodes []string `json:"currency_codes"`
}

// Validate validates this hipstershop get supported currencies response
func (m *HipstershopGetSupportedCurrenciesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopGetSupportedCurrenciesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopGetSupportedCurrenciesResponse) UnmarshalBinary(b []byte) error {
	var res HipstershopGetSupportedCurrenciesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
