// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HipstershopChargeResponse hipstershop charge response
// swagger:model hipstershopChargeResponse
type HipstershopChargeResponse struct {

	// transaction id
	TransactionID string `json:"transaction_id,omitempty"`
}

// Validate validates this hipstershop charge response
func (m *HipstershopChargeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopChargeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopChargeResponse) UnmarshalBinary(b []byte) error {
	var res HipstershopChargeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
