// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HipstershopProduct hipstershop product
// swagger:model hipstershopProduct
type HipstershopProduct struct {

	// Categories such as "vintage" or "gardening" that can be used to look up
	// other related products.
	Categories []string `json:"categories"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// picture
	Picture string `json:"picture,omitempty"`

	// price usd
	PriceUsd *HipstershopMoney `json:"price_usd,omitempty"`
}

// Validate validates this hipstershop product
func (m *HipstershopProduct) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePriceUsd(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HipstershopProduct) validatePriceUsd(formats strfmt.Registry) error {

	if swag.IsZero(m.PriceUsd) { // not required
		return nil
	}

	if m.PriceUsd != nil {
		if err := m.PriceUsd.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("price_usd")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopProduct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopProduct) UnmarshalBinary(b []byte) error {
	var res HipstershopProduct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
