// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HipstershopCreditCardInfo hipstershop credit card info
// swagger:model hipstershopCreditCardInfo
type HipstershopCreditCardInfo struct {

	// credit card cvv
	CreditCardCvv int32 `json:"credit_card_cvv,omitempty"`

	// credit card expiration month
	CreditCardExpirationMonth int32 `json:"credit_card_expiration_month,omitempty"`

	// credit card expiration year
	CreditCardExpirationYear int32 `json:"credit_card_expiration_year,omitempty"`

	// credit card number
	CreditCardNumber string `json:"credit_card_number,omitempty"`
}

// Validate validates this hipstershop credit card info
func (m *HipstershopCreditCardInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopCreditCardInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopCreditCardInfo) UnmarshalBinary(b []byte) error {
	var res HipstershopCreditCardInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
