// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HipstershopAddress hipstershop address
// swagger:model hipstershopAddress
type HipstershopAddress struct {

	// city
	City string `json:"city,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// street address
	StreetAddress string `json:"street_address,omitempty"`

	// zip code
	ZipCode int32 `json:"zip_code,omitempty"`
}

// Validate validates this hipstershop address
func (m *HipstershopAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopAddress) UnmarshalBinary(b []byte) error {
	var res HipstershopAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
