// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HipstershopGetQuoteResponse hipstershop get quote response
// swagger:model hipstershopGetQuoteResponse
type HipstershopGetQuoteResponse struct {

	// cost usd
	CostUsd *HipstershopMoney `json:"cost_usd,omitempty"`
}

// Validate validates this hipstershop get quote response
func (m *HipstershopGetQuoteResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCostUsd(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HipstershopGetQuoteResponse) validateCostUsd(formats strfmt.Registry) error {

	if swag.IsZero(m.CostUsd) { // not required
		return nil
	}

	if m.CostUsd != nil {
		if err := m.CostUsd.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost_usd")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopGetQuoteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopGetQuoteResponse) UnmarshalBinary(b []byte) error {
	var res HipstershopGetQuoteResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
