// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HipstershopChargeRequest hipstershop charge request
// swagger:model hipstershopChargeRequest
type HipstershopChargeRequest struct {

	// amount
	Amount *HipstershopMoney `json:"amount,omitempty"`

	// credit card
	CreditCard *HipstershopCreditCardInfo `json:"credit_card,omitempty"`
}

// Validate validates this hipstershop charge request
func (m *HipstershopChargeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreditCard(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HipstershopChargeRequest) validateAmount(formats strfmt.Registry) error {

	if swag.IsZero(m.Amount) { // not required
		return nil
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *HipstershopChargeRequest) validateCreditCard(formats strfmt.Registry) error {

	if swag.IsZero(m.CreditCard) { // not required
		return nil
	}

	if m.CreditCard != nil {
		if err := m.CreditCard.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("credit_card")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HipstershopChargeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HipstershopChargeRequest) UnmarshalBinary(b []byte) error {
	var res HipstershopChargeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
