// Code generated by go-swagger; DO NOT EDIT.

package ad_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// GetAdsReader is a Reader for the GetAds structure.
type GetAdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAdsOK creates a GetAdsOK with default headers values
func NewGetAdsOK() *GetAdsOK {
	return &GetAdsOK{}
}

/*GetAdsOK handles this case with default header values.

A successful response.
*/
type GetAdsOK struct {
	Payload *models.HipstershopAdResponse
}

func (o *GetAdsOK) Error() string {
	return fmt.Sprintf("[GET /ads][%d] getAdsOK  %+v", 200, o.Payload)
}

func (o *GetAdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopAdResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
