// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// GetQuoteReader is a Reader for the GetQuote structure.
type GetQuoteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQuoteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetQuoteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetQuoteOK creates a GetQuoteOK with default headers values
func NewGetQuoteOK() *GetQuoteOK {
	return &GetQuoteOK{}
}

/*GetQuoteOK handles this case with default header values.

A successful response.
*/
type GetQuoteOK struct {
	Payload *models.HipstershopGetQuoteResponse
}

func (o *GetQuoteOK) Error() string {
	return fmt.Sprintf("[POST /shipping/quote][%d] getQuoteOK  %+v", 200, o.Payload)
}

func (o *GetQuoteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopGetQuoteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
