// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// NewGetQuoteParams creates a new GetQuoteParams object
// with the default values initialized.
func NewGetQuoteParams() *GetQuoteParams {
	var ()
	return &GetQuoteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetQuoteParamsWithTimeout creates a new GetQuoteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetQuoteParamsWithTimeout(timeout time.Duration) *GetQuoteParams {
	var ()
	return &GetQuoteParams{

		timeout: timeout,
	}
}

// NewGetQuoteParamsWithContext creates a new GetQuoteParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetQuoteParamsWithContext(ctx context.Context) *GetQuoteParams {
	var ()
	return &GetQuoteParams{

		Context: ctx,
	}
}

// NewGetQuoteParamsWithHTTPClient creates a new GetQuoteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetQuoteParamsWithHTTPClient(client *http.Client) *GetQuoteParams {
	var ()
	return &GetQuoteParams{
		HTTPClient: client,
	}
}

/*GetQuoteParams contains all the parameters to send to the API endpoint
for the get quote operation typically these are written to a http.Request
*/
type GetQuoteParams struct {

	/*Body*/
	Body *models.HipstershopGetQuoteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get quote params
func (o *GetQuoteParams) WithTimeout(timeout time.Duration) *GetQuoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get quote params
func (o *GetQuoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get quote params
func (o *GetQuoteParams) WithContext(ctx context.Context) *GetQuoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get quote params
func (o *GetQuoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get quote params
func (o *GetQuoteParams) WithHTTPClient(client *http.Client) *GetQuoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get quote params
func (o *GetQuoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get quote params
func (o *GetQuoteParams) WithBody(body *models.HipstershopGetQuoteRequest) *GetQuoteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get quote params
func (o *GetQuoteParams) SetBody(body *models.HipstershopGetQuoteRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetQuoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
