// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new shipping service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for shipping service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetQuote get quote API
*/
func (a *Client) GetQuote(params *GetQuoteParams) (*GetQuoteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetQuoteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetQuote",
		Method:             "POST",
		PathPattern:        "/shipping/quote",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetQuoteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetQuoteOK), nil

}

/*
ShipOrder ship order API
*/
func (a *Client) ShipOrder(params *ShipOrderParams) (*ShipOrderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewShipOrderParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ShipOrder",
		Method:             "POST",
		PathPattern:        "/shipping",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ShipOrderReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ShipOrderOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
