// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// NewShipOrderParams creates a new ShipOrderParams object
// with the default values initialized.
func NewShipOrderParams() *ShipOrderParams {
	var ()
	return &ShipOrderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShipOrderParamsWithTimeout creates a new ShipOrderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShipOrderParamsWithTimeout(timeout time.Duration) *ShipOrderParams {
	var ()
	return &ShipOrderParams{

		timeout: timeout,
	}
}

// NewShipOrderParamsWithContext creates a new ShipOrderParams object
// with the default values initialized, and the ability to set a context for a request
func NewShipOrderParamsWithContext(ctx context.Context) *ShipOrderParams {
	var ()
	return &ShipOrderParams{

		Context: ctx,
	}
}

// NewShipOrderParamsWithHTTPClient creates a new ShipOrderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShipOrderParamsWithHTTPClient(client *http.Client) *ShipOrderParams {
	var ()
	return &ShipOrderParams{
		HTTPClient: client,
	}
}

/*ShipOrderParams contains all the parameters to send to the API endpoint
for the ship order operation typically these are written to a http.Request
*/
type ShipOrderParams struct {

	/*Body*/
	Body *models.HipstershopShipOrderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ship order params
func (o *ShipOrderParams) WithTimeout(timeout time.Duration) *ShipOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ship order params
func (o *ShipOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ship order params
func (o *ShipOrderParams) WithContext(ctx context.Context) *ShipOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ship order params
func (o *ShipOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ship order params
func (o *ShipOrderParams) WithHTTPClient(client *http.Client) *ShipOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ship order params
func (o *ShipOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ship order params
func (o *ShipOrderParams) WithBody(body *models.HipstershopShipOrderRequest) *ShipOrderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ship order params
func (o *ShipOrderParams) SetBody(body *models.HipstershopShipOrderRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ShipOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
