// Code generated by go-swagger; DO NOT EDIT.

package email_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// SendOrderConfirmationReader is a Reader for the SendOrderConfirmation structure.
type SendOrderConfirmationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendOrderConfirmationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendOrderConfirmationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendOrderConfirmationOK creates a SendOrderConfirmationOK with default headers values
func NewSendOrderConfirmationOK() *SendOrderConfirmationOK {
	return &SendOrderConfirmationOK{}
}

/*SendOrderConfirmationOK handles this case with default header values.

A successful response.
*/
type SendOrderConfirmationOK struct {
	Payload models.HipstershopEmpty
}

func (o *SendOrderConfirmationOK) Error() string {
	return fmt.Sprintf("[POST /sendmail][%d] sendOrderConfirmationOK  %+v", 200, o.Payload)
}

func (o *SendOrderConfirmationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
