// Code generated by go-swagger; DO NOT EDIT.

package email_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// NewSendOrderConfirmationParams creates a new SendOrderConfirmationParams object
// with the default values initialized.
func NewSendOrderConfirmationParams() *SendOrderConfirmationParams {
	var ()
	return &SendOrderConfirmationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendOrderConfirmationParamsWithTimeout creates a new SendOrderConfirmationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendOrderConfirmationParamsWithTimeout(timeout time.Duration) *SendOrderConfirmationParams {
	var ()
	return &SendOrderConfirmationParams{

		timeout: timeout,
	}
}

// NewSendOrderConfirmationParamsWithContext creates a new SendOrderConfirmationParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendOrderConfirmationParamsWithContext(ctx context.Context) *SendOrderConfirmationParams {
	var ()
	return &SendOrderConfirmationParams{

		Context: ctx,
	}
}

// NewSendOrderConfirmationParamsWithHTTPClient creates a new SendOrderConfirmationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendOrderConfirmationParamsWithHTTPClient(client *http.Client) *SendOrderConfirmationParams {
	var ()
	return &SendOrderConfirmationParams{
		HTTPClient: client,
	}
}

/*SendOrderConfirmationParams contains all the parameters to send to the API endpoint
for the send order confirmation operation typically these are written to a http.Request
*/
type SendOrderConfirmationParams struct {

	/*Body*/
	Body *models.HipstershopSendOrderConfirmationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send order confirmation params
func (o *SendOrderConfirmationParams) WithTimeout(timeout time.Duration) *SendOrderConfirmationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send order confirmation params
func (o *SendOrderConfirmationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send order confirmation params
func (o *SendOrderConfirmationParams) WithContext(ctx context.Context) *SendOrderConfirmationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send order confirmation params
func (o *SendOrderConfirmationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send order confirmation params
func (o *SendOrderConfirmationParams) WithHTTPClient(client *http.Client) *SendOrderConfirmationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send order confirmation params
func (o *SendOrderConfirmationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send order confirmation params
func (o *SendOrderConfirmationParams) WithBody(body *models.HipstershopSendOrderConfirmationRequest) *SendOrderConfirmationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send order confirmation params
func (o *SendOrderConfirmationParams) SetBody(body *models.HipstershopSendOrderConfirmationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SendOrderConfirmationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
