// Code generated by go-swagger; DO NOT EDIT.

package currency_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// ConvertReader is a Reader for the Convert structure.
type ConvertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConvertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewConvertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConvertOK creates a ConvertOK with default headers values
func NewConvertOK() *ConvertOK {
	return &ConvertOK{}
}

/*ConvertOK handles this case with default header values.

A successful response.
*/
type ConvertOK struct {
	Payload *models.HipstershopMoney
}

func (o *ConvertOK) Error() string {
	return fmt.Sprintf("[GET /currencies/convert/{from.currency_code}/{to_code}][%d] convertOK  %+v", 200, o.Payload)
}

func (o *ConvertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopMoney)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
