// Code generated by go-swagger; DO NOT EDIT.

package currency_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new currency service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for currency service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
Convert convert API
*/
func (a *Client) Convert(params *ConvertParams) (*ConvertOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConvertParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Convert",
		Method:             "GET",
		PathPattern:        "/currencies/convert/{from.currency_code}/{to_code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ConvertReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ConvertOK), nil

}

/*
GetSupportedCurrencies get supported currencies API
*/
func (a *Client) GetSupportedCurrencies(params *GetSupportedCurrenciesParams) (*GetSupportedCurrenciesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSupportedCurrenciesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetSupportedCurrencies",
		Method:             "GET",
		PathPattern:        "/currencies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSupportedCurrenciesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSupportedCurrenciesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
