// Code generated by go-swagger; DO NOT EDIT.

package currency_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// GetSupportedCurrenciesReader is a Reader for the GetSupportedCurrencies structure.
type GetSupportedCurrenciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSupportedCurrenciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSupportedCurrenciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSupportedCurrenciesOK creates a GetSupportedCurrenciesOK with default headers values
func NewGetSupportedCurrenciesOK() *GetSupportedCurrenciesOK {
	return &GetSupportedCurrenciesOK{}
}

/*GetSupportedCurrenciesOK handles this case with default header values.

A successful response.
*/
type GetSupportedCurrenciesOK struct {
	Payload *models.HipstershopGetSupportedCurrenciesResponse
}

func (o *GetSupportedCurrenciesOK) Error() string {
	return fmt.Sprintf("[GET /currencies][%d] getSupportedCurrenciesOK  %+v", 200, o.Payload)
}

func (o *GetSupportedCurrenciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopGetSupportedCurrenciesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
