// Code generated by go-swagger; DO NOT EDIT.

package currency_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSupportedCurrenciesParams creates a new GetSupportedCurrenciesParams object
// with the default values initialized.
func NewGetSupportedCurrenciesParams() *GetSupportedCurrenciesParams {

	return &GetSupportedCurrenciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSupportedCurrenciesParamsWithTimeout creates a new GetSupportedCurrenciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSupportedCurrenciesParamsWithTimeout(timeout time.Duration) *GetSupportedCurrenciesParams {

	return &GetSupportedCurrenciesParams{

		timeout: timeout,
	}
}

// NewGetSupportedCurrenciesParamsWithContext creates a new GetSupportedCurrenciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSupportedCurrenciesParamsWithContext(ctx context.Context) *GetSupportedCurrenciesParams {

	return &GetSupportedCurrenciesParams{

		Context: ctx,
	}
}

// NewGetSupportedCurrenciesParamsWithHTTPClient creates a new GetSupportedCurrenciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSupportedCurrenciesParamsWithHTTPClient(client *http.Client) *GetSupportedCurrenciesParams {

	return &GetSupportedCurrenciesParams{
		HTTPClient: client,
	}
}

/*GetSupportedCurrenciesParams contains all the parameters to send to the API endpoint
for the get supported currencies operation typically these are written to a http.Request
*/
type GetSupportedCurrenciesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get supported currencies params
func (o *GetSupportedCurrenciesParams) WithTimeout(timeout time.Duration) *GetSupportedCurrenciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get supported currencies params
func (o *GetSupportedCurrenciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get supported currencies params
func (o *GetSupportedCurrenciesParams) WithContext(ctx context.Context) *GetSupportedCurrenciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get supported currencies params
func (o *GetSupportedCurrenciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get supported currencies params
func (o *GetSupportedCurrenciesParams) WithHTTPClient(client *http.Client) *GetSupportedCurrenciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get supported currencies params
func (o *GetSupportedCurrenciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSupportedCurrenciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
