// Code generated by go-swagger; DO NOT EDIT.

package cart_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// AddItemReader is a Reader for the AddItem structure.
type AddItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddItemOK creates a AddItemOK with default headers values
func NewAddItemOK() *AddItemOK {
	return &AddItemOK{}
}

/*AddItemOK handles this case with default header values.

A successful response.
*/
type AddItemOK struct {
	Payload models.HipstershopEmpty
}

func (o *AddItemOK) Error() string {
	return fmt.Sprintf("[POST /carts][%d] addItemOK  %+v", 200, o.Payload)
}

func (o *AddItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
