// Code generated by go-swagger; DO NOT EDIT.

package cart_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmptyCartParams creates a new EmptyCartParams object
// with the default values initialized.
func NewEmptyCartParams() *EmptyCartParams {
	var ()
	return &EmptyCartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmptyCartParamsWithTimeout creates a new EmptyCartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmptyCartParamsWithTimeout(timeout time.Duration) *EmptyCartParams {
	var ()
	return &EmptyCartParams{

		timeout: timeout,
	}
}

// NewEmptyCartParamsWithContext creates a new EmptyCartParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmptyCartParamsWithContext(ctx context.Context) *EmptyCartParams {
	var ()
	return &EmptyCartParams{

		Context: ctx,
	}
}

// NewEmptyCartParamsWithHTTPClient creates a new EmptyCartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmptyCartParamsWithHTTPClient(client *http.Client) *EmptyCartParams {
	var ()
	return &EmptyCartParams{
		HTTPClient: client,
	}
}

/*EmptyCartParams contains all the parameters to send to the API endpoint
for the empty cart operation typically these are written to a http.Request
*/
type EmptyCartParams struct {

	/*UserID*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the empty cart params
func (o *EmptyCartParams) WithTimeout(timeout time.Duration) *EmptyCartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the empty cart params
func (o *EmptyCartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the empty cart params
func (o *EmptyCartParams) WithContext(ctx context.Context) *EmptyCartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the empty cart params
func (o *EmptyCartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the empty cart params
func (o *EmptyCartParams) WithHTTPClient(client *http.Client) *EmptyCartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the empty cart params
func (o *EmptyCartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the empty cart params
func (o *EmptyCartParams) WithUserID(userID string) *EmptyCartParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the empty cart params
func (o *EmptyCartParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *EmptyCartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
