// Code generated by go-swagger; DO NOT EDIT.

package cart_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// EmptyCartReader is a Reader for the EmptyCart structure.
type EmptyCartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmptyCartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmptyCartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmptyCartOK creates a EmptyCartOK with default headers values
func NewEmptyCartOK() *EmptyCartOK {
	return &EmptyCartOK{}
}

/*EmptyCartOK handles this case with default header values.

A successful response.
*/
type EmptyCartOK struct {
	Payload models.HipstershopEmpty
}

func (o *EmptyCartOK) Error() string {
	return fmt.Sprintf("[DELETE /carts/{user_id}][%d] emptyCartOK  %+v", 200, o.Payload)
}

func (o *EmptyCartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
