// Code generated by go-swagger; DO NOT EDIT.

package cart_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCartParams creates a new GetCartParams object
// with the default values initialized.
func NewGetCartParams() *GetCartParams {
	var ()
	return &GetCartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCartParamsWithTimeout creates a new GetCartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCartParamsWithTimeout(timeout time.Duration) *GetCartParams {
	var ()
	return &GetCartParams{

		timeout: timeout,
	}
}

// NewGetCartParamsWithContext creates a new GetCartParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCartParamsWithContext(ctx context.Context) *GetCartParams {
	var ()
	return &GetCartParams{

		Context: ctx,
	}
}

// NewGetCartParamsWithHTTPClient creates a new GetCartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCartParamsWithHTTPClient(client *http.Client) *GetCartParams {
	var ()
	return &GetCartParams{
		HTTPClient: client,
	}
}

/*GetCartParams contains all the parameters to send to the API endpoint
for the get cart operation typically these are written to a http.Request
*/
type GetCartParams struct {

	/*UserID*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cart params
func (o *GetCartParams) WithTimeout(timeout time.Duration) *GetCartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cart params
func (o *GetCartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cart params
func (o *GetCartParams) WithContext(ctx context.Context) *GetCartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cart params
func (o *GetCartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cart params
func (o *GetCartParams) WithHTTPClient(client *http.Client) *GetCartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cart params
func (o *GetCartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get cart params
func (o *GetCartParams) WithUserID(userID string) *GetCartParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get cart params
func (o *GetCartParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
