// Code generated by go-swagger; DO NOT EDIT.

package product_catalog_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// SearchProductsReader is a Reader for the SearchProducts structure.
type SearchProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchProductsOK creates a SearchProductsOK with default headers values
func NewSearchProductsOK() *SearchProductsOK {
	return &SearchProductsOK{}
}

/*SearchProductsOK handles this case with default header values.

A successful response.
*/
type SearchProductsOK struct {
	Payload *models.HipstershopSearchProductsResponse
}

func (o *SearchProductsOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] searchProductsOK  %+v", 200, o.Payload)
}

func (o *SearchProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HipstershopSearchProductsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
