// Code generated by go-swagger; DO NOT EDIT.

package product_catalog_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/siriscac/microservices-demo/fontend/apiclient/models"
)

// NewSearchProductsParams creates a new SearchProductsParams object
// with the default values initialized.
func NewSearchProductsParams() *SearchProductsParams {
	var ()
	return &SearchProductsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchProductsParamsWithTimeout creates a new SearchProductsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchProductsParamsWithTimeout(timeout time.Duration) *SearchProductsParams {
	var ()
	return &SearchProductsParams{

		timeout: timeout,
	}
}

// NewSearchProductsParamsWithContext creates a new SearchProductsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchProductsParamsWithContext(ctx context.Context) *SearchProductsParams {
	var ()
	return &SearchProductsParams{

		Context: ctx,
	}
}

// NewSearchProductsParamsWithHTTPClient creates a new SearchProductsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchProductsParamsWithHTTPClient(client *http.Client) *SearchProductsParams {
	var ()
	return &SearchProductsParams{
		HTTPClient: client,
	}
}

/*SearchProductsParams contains all the parameters to send to the API endpoint
for the search products operation typically these are written to a http.Request
*/
type SearchProductsParams struct {

	/*Body*/
	Body *models.HipstershopSearchProductsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search products params
func (o *SearchProductsParams) WithTimeout(timeout time.Duration) *SearchProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search products params
func (o *SearchProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search products params
func (o *SearchProductsParams) WithContext(ctx context.Context) *SearchProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search products params
func (o *SearchProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search products params
func (o *SearchProductsParams) WithHTTPClient(client *http.Client) *SearchProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search products params
func (o *SearchProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search products params
func (o *SearchProductsParams) WithBody(body *models.HipstershopSearchProductsRequest) *SearchProductsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search products params
func (o *SearchProductsParams) SetBody(body *models.HipstershopSearchProductsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
